### ISSUE TITLE
sjsonnet.Error: Internal Error caused by java.lang.StackOverflowError with deep recursion

### ISSUE THREAD

**Issue by sbarzowski** [databricks/sjsonnet#10]
I'm working on go-jsonnet performance and I was trying to compare function call performance across implementations. I tried running the following benchmark:

```
local f2(f) = function(x) f(f(x));
local id(x) = x;

local slowId = std.makeArray(20, function(i) if i == 0 then id else f2(slowId[i - 1]));

slowId[15](42)
```

It resulted in the following error:
```
sjsonnet.Error: Internal Error
    at .(bench.07.jsonnet:2:15)
    at .(bench.07.jsonnet:1:28)
    at .(bench.07.jsonnet:1:30)
[many similar lines omitted]
    at .(bench.07.jsonnet:1:28)
    at .(bench.07.jsonnet:1:28)
    at .(bench.07.jsonnet:6:11)
Caused by: java.lang.StackOverflowError
    at sun.nio.fs.NativeBuffers.getNativeBufferFromCache(NativeBuffers.java:58)
    at sun.nio.fs.UnixNativeDispatcher.copyToNativeBuffer(UnixNativeDispatcher.java:42)
    at sun.nio.fs.UnixNativeDispatcher.open(UnixNativeDispatcher.java:69)
    at sun.nio.fs.UnixChannelFactory.open(UnixChannelFactory.java:257)
[many similar lines omitted]
```

To run this code with google/jsonnet or google/go-jsonnet the stack size needs to be increased with a command line option (e.g. `-s 1000000`).

Is there an option I could pass or something?

**Comment by lihaoyi** [comment]
@sbarzowski Can you try increasing the stack size via https://stackoverflow.com/questions/3700459/how-to-increase-the-java-stack-size ? I haven't done much stack-size-fiddling myself, but it should work if your thing is just deep-recursive and not infinite-recursive

**Comment by lihaoyi** [comment]
(You'd need to pass that flag to the JVM rather than Sjsonnet, so something like `java -Xss4m -cp sjsonnet.jar sjsonnet.Main foo.jsonnet` to run it on a file)

**Comment by sbarzowski** [comment]
Thanks. It worked after some tweaking:
```
java -Xss500m -cp sjsonnet.jar sjsonnet.SjsonnetMain bench.07.jsonnet
```

Should I create a PR which adds this info to README?

**Comment by lihaoyi** [comment]
@sbarzowski sure!

**Comment by sbarzowski** [comment]
Ok, I've just sent #11
