### ISSUE TITLE
Build sjsonnet with Scala Native or GraalVM?

### ISSUE THREAD

**Issue by olorin37** [databricks/sjsonnet#123]
Have you any plans to build sjsonnet with Scala Native or GraalVM it could bring better performance.

**Comment by farquet** [comment]
FWIW, in the GraalVM team we are heavy jsonnet users to define CI jobs. See the jsonnet files spread in the graal repository: https://github.com/oracle/graal
We have experimented with different jsonnet implementations and `sjsonnet` is the best and super fast! It also compiles out of the box with GraalVM Native Image and gives an extra significant boost.

For reference, here are the numbers of seconds required to generate our CI files with different implementations:
![GraalVM CI files](https://user-images.githubusercontent.com/2393555/183022862-298270de-d067-417b-a7d7-c699808d847b.png)

**Comment by olorin37** [comment]
Can you share how you compile `sjsonnet` with graalVM Native? What NI EE and NI EE PGO stands for?

**Comment by rschatz** [comment]
I don't know the exact commands @farquet used, but for me, just running `native-image --no-fallback -jar sjsonnet.jar` works.

`NI EE` is "native-image enterprise edition"
`NI EE PGO` is "native-image enterprise edition with profile-guided optimizations (https://www.graalvm.org/22.1/reference-manual/native-image/PGO/)"

**Comment by lihaoyi-databricks** [comment]
Going to close this, since Sjsonnet is already built using Scala-Native (https://medium.com/virtuslab/revisiting-scala-native-performance-67029089f241), and you can always build your own native images with the commands above.
