### ISSUE TITLE
Safe select operator

### ISSUE THREAD

**Issue by jam01** [databricks/sjsonnet#124]
It would be useful to have a selector notation that was null safe. Perhaps `?.` as Kotlin has https://kotlinlang.org/docs/null-safety.html#safe-calls

```
{x: 1}?.y
```
would return `null` instead of throwing an error

Edit: realized that this is something that would have to be added to jsonnet first. I've opened the same item on that project.

**Comment by lihaoyi-databricks** [comment]
Gonna close this for now; we can re-open it when it's implemented upstream
