### ISSUE TITLE
+: is erroneously interpreted as : within object comprehension

### ISSUE THREAD

**Issue by NicholasHusin** [databricks/sjsonnet#154]
Given the following:
```
{ ['foo']+: [x] for x in [1]} + { ['foo']+: [x] for x in [2]}
```
The official implementation of `jsonnet` would output:
```
{
  "foo": [
    1,
    2
  ]
}
```
due to the `+:` used.

However, on `sjsonnet`, the `+` in `+:` seems to be ignored, resulting in
```
{ ['foo']+: [x] for x in [1]} + { ['foo']+: [x] for x in [2]}
```
being interpreted as:
```
{ ['foo']: [x] for x in [1]} + { ['foo']: [x] for x in [2]}
```
and resulting in:
```
{
  "foo": [
    2
  ]
}
```
This causes an inconsistency between `jsonnet` and `sjsonnet`.

**Comment by lihaoyi-databricks** [comment]
Should be fixed by https://github.com/databricks/sjsonnet/pull/155
