### ISSUE TITLE
Is it possible for sjsonnet to parse a Jsonnet string?

### ISSUE THREAD

**Issue by yongxin-db** [databricks/sjsonnet#177]
A quick question: is it possible to give sjsonnet a Jsonnet string and let it parse the string to a `ujson.Value`, instead of giving it a Path?
E.g. something like
```scala
val jsonValue: ujson.Value = sjsonnet.interprete("local jsonnetField = ...")
```
I looked at the code and it seems the only way to invoke sjsonnet is through giving it a file path.

**Comment by yongxin-db** [comment]
cc @lihaoyi-databricks

**Comment by lihaoyi-databricks** [comment]
You can probably do this using the `Interpreter#evaluate` API https://github.com/databricks/sjsonnet/blob/3a3e2521f998955b717d9c9167fa7585ea30d306/sjsonnet/src/sjsonnet/Interpreter.scala#L78
