### ISSUE TITLE
unable to build a local jar 

### ISSUE THREAD

**Issue by sandys** [databricks/sjsonnet#179]
hi,
we are trying to get a build with this pull request - https://github.com/databricks/sjsonnet/pull/166

we tried building using `./mill -i show sjsonnet[2.13.4].jvm.assembly` and picking up `out/sjsonnet/2.13.4/jvm/assembly.dest/out.jar` ,  but the jar is not runnable on commandline like the release jar. it also doesnt run with `java -Xss100m -cp sjsonnet.jar sjsonnet.SjsonnetMain foo.jsonnet` (Both Databricks and our own don't work with this)

we also tried `./mill show sjsonnet[2.13.4].assembly`, but we ran into errors (` Cannot resolve sjsonnet[2.13.4].assembly. Try `mill resolve sjsonnet[2.13.4]._` to see what's available.`).

could you please help out by specifying the exact commandline you use to build the final release jar ? we are using github actions to build and will be using this inside maven pom.xml

**Comment by lihaoyi-databricks** [comment]
Can you try `./mill show sjsonnet[2.13.4].jvm.assembly`
