### ISSUE TITLE
--tla-code does not parse spaces correctly

### ISSUE THREAD

**Issue by vijayklein-db** [databricks/sjsonnet#187]
If there is a space inside the `--tla-code` parameter, sjsonnet will fail to parse it correctly, whereas go-jsonnet works correctly. This can be reproduced by placing the following into `test.jsonnet`

```
function(a) {
  test: a
}
```
and running `$jsonnet_bin test.jsonnet --tla-code 'a="5 4"'`

On go-jsonnet, we correctly see
```
{
   "test": "5 4"
}
```

but on sjsonnet, we see
```
Unknown argument: "4\""
Expected Signature: Sjsonnet 0.4.5
usage: sjsonnet [sjsonnet-options] script-file
  -i --interactive                      Run Mill in interactive mode, suitable for opening REPLs and
                                        taking user input
...
```

**Comment by vijayklein-db** [comment]
This specifically was noticed because trying to import other files within a `--tla-code` was failing, but I later realized it causes issues for **any** space in the passed param.

**Comment by stephenamar-db** [comment]
this is now working in HEAD
