### ISSUE TITLE
How can we use external layer of jsonnet library over it ?

### ISSUE THREAD

**Issue by mrinal1209** [databricks/sjsonnet#20]
I want to use https://github.com/grafana/grafonnet-lib with this library. Can anyone help me how would I configure it? The official google/jsonnet provides this syntax:- { jsonnet -J <lib-path> file.jsonnet } where I can mention a library over their compiler. How can I do the same with this sjsonnet compiler?

**Comment by mrinal1209** [comment]
@lihaoyi @lihaoyi-databricks  @pvid @mgyucht  can anyone of you help me with my query?

**Comment by pvid** [comment]
Hi @mrinal1209! `sjsonnet` has the same flag `-J` and as far as I know, it does the same thing as google/jsonnet. Please consult the help
