### ISSUE TITLE
sjsonnet reverses input args order for std.mapWithIndex

### ISSUE THREAD

**Issue by ericwang-db** [databricks/sjsonnet#26]
According to the [spec](https://jsonnet.org/ref/stdlib.html) the function for mapWithIndex takes the `index` as the first arg, and `elem` as the second. In practice, I've noticed sjsonnet does the opposite by reversing the inde

Here's a simple repro:
foo.jsonnet
```
local x = ["a","b","c"];
{
  result: std.mapWithIndex(function(left, right) left + std.toString(right), x),
}
```

sjsonnet:
```
% sjsonnet foo.jsonnet
{
   "result": [
      "a0",
      "b1",
      "c2"
   ]
}
```

Actual jsonnet:
```
% jsonnet.old foo.jsonnet
{
   "result": [
      "0a",
      "1b",
      "2c"
   ]
}
```

**Comment by lihaoyi-databricks** [comment]
This can be closed i think
