### ISSUE TITLE
sjsonnet behaves differently with handling slicing

### ISSUE THREAD

**Issue by ericwang-db** [databricks/sjsonnet#27]
sjsonnet works but jsonnet doesn't. Here's an example:
foo.jsonnet:
```
local x = ["a","b","c"];
{
  result: std.mapWithIndex(function(left, right) x[0:right], x),
}
```

sjsonnet:
```
% sjsonnet foo.jsonnet
{
   "result": [
      [ ],
      [
         "a"
      ],
      [
         "a",
         "b"
      ]
   ]
}
```

regular jsonnet:
```
% jsonnet.old foo.jsonnet
RUNTIME ERROR: binary operator < requires matching types, got string and number.
	std.jsonnet:200:27-40	function <anonymous>
	foo.jsonnet:3:50-60	function <func>
	std.jsonnet:245:50-65	thunk <array_element>
	foo.jsonnet:3:11-64	object <anonymous>
	During manifestation
```

**Comment by lihaoyi-databricks** [comment]
@ericwang-db I'm having trouble figuring out how come this snippet ends up throwing that error. Do you think it's possible to minimize further?

**Comment by ericwang-db** [comment]
I think this issue is related to https://github.com/databricks/sjsonnet/issues/26, since the arguments being used to the slice the array were incorrect. The error was that the slice that was being materialized from `x[0:"a"]`, so it was complaining that the types are mismatching. I could trigger the same error via running `jsonnet` on `[1,2,3][0:"a"]`. I will close this ticket now.
