### ISSUE TITLE
Artifact ID is incorrect in README

### ISSUE THREAD

**Issue by wiseman** [databricks/sjsonnet#34]
The README says `<artifactId>sjsonnet_2.13</artifactId>`, but maven doesn't have that.  It does have this, however:

```
<dependency>
  <groupId>com.lihaoyi</groupId>
  <artifactId>sjsonnet-2.13.0_2.13</artifactId>
  <version>0.1.4</version>
</dependency>
```

P.S. Why is there what appears to be a version number in the artifact ID?  I don't know Scala--is that a Scala thing?

**Comment by lihaoyi** [comment]
should be fixed in 0.1.5 i think
