### ISSUE TITLE
More complete java example

### ISSUE THREAD

**Issue by wiseman** [databricks/sjsonnet#35]
Is there a more complete Java example for someone that hasn't used scala code from Java before? I haven't been able to find any Java code that uses this library to use as an example.

**Comment by lihaoyi-databricks** [comment]
The documentation example should be all your need. It exposes the same interface as the command line, flags and all, so you should be able to use it without needing to dig deeply into the internals

**Comment by wiseman** [comment]
What about `scala.None$.empty()`? Is that required?
