### ISSUE TITLE
Performance optimization for online processing

### ISSUE THREAD

**Issue by lilac** [databricks/sjsonnet#4]
I intend to use this library as a json rendering engine for an online web service. However, my benchmark result shows that it is about 10 times slower than other mainstream template engine.

```
Benchmark              Mode  Cnt      Score      Error  Units

Freemarker.benchmark  thrpt   50  19696.761 ±  238.828  ops/s

Handlebars.benchmark  thrpt   50  22612.155 ±  188.023  ops/s

Mustache.benchmark    thrpt   50  24847.334 ±  382.594  ops/s

Pebble.benchmark      thrpt   50  41618.048 ± 1239.713  ops/s

Rocker.benchmark      thrpt   50  45752.331 ±  982.167  ops/s

Thymeleaf.benchmark   thrpt   50   1655.655 ±   14.719  ops/s

Trimou.benchmark      thrpt   50  27233.316 ±  290.317  ops/s

Velocity.benchmark    thrpt   50  24459.855 ±  256.733  ops/s

Jsonnet.benchmark  thrpt   50  3615.504 ± 58.233  ops/s
```

Do you have any plan or idea to optimize the interpreter to suit web server scene?

**Comment by lihaoyi-databricks** [comment]
@lilac not terribly surprised Jsonnet is slower, given it's a full interpreter rather than just string-mangling, but any performance improvements are welcome.

If you have the source code of your benchmarks, I'd be happy to add them to this repository so others can run them and contribute
