### ISSUE TITLE
std.rstripChars not supported

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [databricks/sjsonnet#67]
I tried to run sjsonnet on our existing setup and got:

```
sjsonnet.Error: Field does not exist: rstripChars
```

It's from the stdlib: https://github.com/google/jsonnet/blob/29fd57097fba5bb9fa90038e855b1bd1ee0901c0/stdlib/std.jsonnet#L63.

There's probably other things missing for parity too, e.g. https://github.com/databricks/sjsonnet/issues/66.

**Comment by lihaoyi-databricks** [comment]
Fixed by https://github.com/databricks/sjsonnet/pull/79
