### ISSUE TITLE
Request to rerun benchmarks against latest go-jsonnet

### ISSUE THREAD

**Issue by ghostsquad** [databricks/sjsonnet#71]
This is a request to rerun & post/update the benchmarks comparing sjsonnet to go-jsonnet. Some recent PRs have been made to move some of the most costly stdlib functions into native Go code.

I used https://github.com/coreos/kube-prometheus?ts=4 as a test bed, the `./build.sh` script generates a lot of files.

My preliminary wall clock tests:

`go-jsonnet`
```
2.89 real         4.22 user         0.85 sys
2.85 real         4.20 user         0.80 sys
2.93 real         4.25 user         0.87 sys
2.94 real         4.24 user         0.87 sys
3.13 real         4.41 user         0.85 sys
```

`sjsonnet`
```
3.63 real         7.56 user         1.03 sys
3.60 real         6.32 user         0.92 sys
3.59 real         6.26 user         0.88 sys
3.94 real         6.47 user         0.95 sys
3.88 real         6.44 user         0.87 sys
```

**Comment by ghostsquad** [comment]
Modifying `./build.sh` to use `$JSONNET` instead of `jsonnet` and leveraging https://github.com/sharkdp/hyperfine?ts=4 to give me some accurate results.

```
❯ JSONNET=$HOME/bin/sjsonnet.jar hyperfine --warmup 3 -m 20 ./build.sh
Benchmark #1: ./build.sh
  Time (mean ± σ):      3.392 s ±  0.151 s    [User: 7.763 s, System: 1.003 s]
  Range (min … max):    3.257 s …  3.812 s    20 runs
```

```
❯ JSONNET=$GOPATH/bin/jsonnet hyperfine --warmup 3 -m 20 ./build.sh
Benchmark #1: ./build.sh
  Time (mean ± σ):      2.930 s ±  0.150 s    [User: 4.184 s, System: 0.844 s]
  Range (min … max):    2.771 s …  3.301 s    20 runs
```

**Comment by lihaoyi-databricks** [comment]
Re-ran some ad-hoc benchmarks a few days ago and updated the readme


|              | Sjsonnet 0.4.3 | google/go-jsonnet 0.20.0 | google/jsonnet 0.20.0 |
| :----------- | -------------: | -------------: | -------------: |
| staging/runbot-app.jsonnet (~6.6mb output JSON) | ~0.10s |  ~6.5s | ~67s |

Might not be super precise, but should be about the right order of magnitude of the relevant performance of Sjsonnet, google/go-jsonnet, and google/jsonnet

**Comment by ghostsquad** [comment]
There's still quite a few functions that are still not moved over to Golang (still written in Jsonnet). I think that is what your benchmarks are showing. Would be awesome to have some more contributors to `go-jsonnet` to move those functions over.
