### ISSUE TITLE
main0 should print to the provided stdIn

### ISSUE THREAD

**Issue by jatcwang** [databricks/sjsonnet#72]
https://github.com/databricks/sjsonnet/blob/298b765310158b1a8bae3eef1dc54b59f34fd417/sjsonnet/src-jvm/sjsonnet/SjsonnetMain.scala#L45

The `stdOut` parameter in `main0` is unused but seems like it was intended to be used.
Will raise a PR if you can confirm that it should use the provided `stdOut` instead of always printing to System.out?

(I'd like to programmatically use sjsonnet instead of calling it from CLI)

**Comment by johnhorton2010** [comment]
It looks like this has been resolved to use the stderr and stdout that is passed in to main0.

https://github.com/databricks/sjsonnet/blob/80b2657ae2b77667013adfdc413b025ff6b0a95a/sjsonnet/src-jvm/sjsonnet/SjsonnetMain.scala#L77-L84

**Comment by jatcwang** [comment]
Thanks @johnhorton2010. I'll reopen if it doesn't work
