### ISSUE TITLE
std.slice builtin does not exist

### ISSUE THREAD

**Issue by Qinusty** [databricks/sjsonnet#74]
The std.slice function is not implemented in sjsonnet. This is currently [missing](https://github.com/google/jsonnet/issues/798) from the upstream documentation but implemented in both google/jsonnet and google/go-jsonnet.

This is seen within [stdlib.jsonnet](https://github.com/google/jsonnet/blob/master/stdlib/std.jsonnet#L191) in google/jsonnet.

This is an incompatibility issue as tracked by #73

**Comment by markj-db** [comment]
std.slice is now included in upstream documentation: https://jsonnet.org/ref/stdlib.html
