### ISSUE TITLE
Missing implementation of std.member

### ISSUE THREAD

**Issue by markj-db** [databricks/sjsonnet#80]
https://jsonnet.org/ref/stdlib.html

std.member(arr, x)
Available since version 0.15.0.
Returns whether x occurs in arr. Argument arr may be an array or a string.

This is used in https://github.com/jsonnet-libs/xtd

Version 0.15.0 introduced several new functions in the std library:

New stdlib functions:
std.member
std.clamp
std.stripChars, std.lstripChars, std.stripChars
std.flatMap
std.repeat

https://github.com/google/jsonnet/releases

**Comment by markj-db** [comment]
This is another incompatibility with standard jsonnet https://github.com/databricks/sjsonnet/issues/73

**Comment by markj-db** [comment]
And is a duplicate of https://github.com/databricks/sjsonnet/issues/66

**Comment by lihaoyi-databricks** [comment]
Fixed by https://github.com/databricks/sjsonnet/pull/81
