### ISSUE TITLE
the default CLI output is incomplete , shows a lot of '???'

### ISSUE THREAD

**Issue by xask00** [databricks/sjsonnet#9]
# ./sjsonnet.jar 
error: Need to pass in a jsonnet file to evaluate
usage: sjsonnet [sjsonnet-options] script-file

  -i, --interactive  Run Mill in interactive mode, suitable for opening REPLs and taking user input
  -n, --indent       How much to indent your output JSON
  -J, --jpath        Specify an additional library search dir (right-most wins)
  -o, --output-file  Write to the output file rather than stdout
  -V, --ext-str      ???
  --ext-str-file     ???
  --ext-code         ???
  --ext-code-file    ???
  -A, --tla-str      ???
  --tla-str-file     ???
  --tla-code         ???
  --tla-code-file    ???

**Comment by lihaoyi** [comment]
Haha yeah, this is just me being sloppy. These flags are all fully implemented, just not documented properly. A PR to copy over the messages from the Go or C++ Jsonnet help output would be welcome!
