### ISSUE TITLE
RFE: parseYAML

### ISSUE THREAD

**Issue by derrickburns** [databricks/sjsonnet#91]
Can you add a function to parse a YAML string?

**Comment by lihaoyi-databricks** [comment]
@derrickburns could you open this as an issue on the http://github.com/google/jsonnet repository? Sjsonnet largely tries to follow google/jsonnet's behavior as closely as possible, and doesn't make any language or library innovations on its own. If google/jsonnet adds such a function, we'll do so as well, if not we won't

**Comment by olorin37** [comment]
Hello, in fact it exists almost ready [PR 888](https://github.com/google/jsonnet/pull/888) for introducing `std.parseYaml` in google/jsonnet, and possibly it can be accepted when problems will be solved.

**Comment by olorin37** [comment]
Currently `std.parseYaml` is already merged to both reference implementations (C++: https://github.com/google/jsonnet/pull/899 and Go: https://github.com/google/go-jsonnet/pull/339 versions). It is already on their masters, but not released in any tag yet.

So, it looks like good time to start implementation in sjsonnet.

**Comment by lihaoyi-databricks** [comment]
This finally landed in 0.4.6 https://github.com/databricks/sjsonnet/pull/142
